package decoder

// spec7_report_test.go renders the derived GEDCOM 7.0 inventory as the
// published reference document. It makes no measurements of its own: every
// number below is counted from the entries spec7_coverage_test.go produced.

import (
	"fmt"
	"sort"
	"strings"
)

// spec7StatusOrder fixes the order statuses are reported in, best first.
var spec7StatusOrder = []spec7Status{
	spec7Typed, spec7Partial, spec7RawAccepted, spec7RawFlagged, spec7RawUnwatched,
}

// spec7StatusMeaning explains each status where it is first tabulated, so the
// summary is readable without the methodology section.
var spec7StatusMeaning = map[spec7Status]string{
	spec7Typed:        "Decoded into the typed model; reachable without walking `Record.Tags`.",
	spec7Partial:      "Reaches the typed model but is still reported as an unknown tag.",
	spec7RawAccepted:  "Raw tags only. The decoder reads this context and knows the tag, but has no typed field for it.",
	spec7RawFlagged:   "Raw tags only. The decoder reads this context and reports the tag as unknown.",
	spec7RawUnwatched: "Raw tags only. The decoder does not read this context, so nothing in it is ever reported.",
}

// spec7Group is the set of entries sharing one superstructure.
type spec7Group struct {
	context string
	term    string
	entries []spec7Entry
}

// spec7Document renders the whole reference document.
func spec7Document(spec *spec7Spec, entries []spec7Entry) string {
	var sb strings.Builder

	sb.WriteString(spec7Preamble(spec, entries))
	sb.WriteString(spec7Summary(entries))
	sb.WriteString(spec7Inventory(entries))

	return sb.String()
}

// spec7Preamble writes the title, what the document is, and where its two
// inputs -- the specification and the decoder -- come from.
func spec7Preamble(spec *spec7Spec, entries []spec7Entry) string {
	return fmt.Sprintf(`<!-- Generated by decoder/spec7_coverage_test.go. Do not edit by hand. -->

# GEDCOM 7.0 coverage

What this library does with every structure GEDCOM 7.0 defines: %d
(superstructure, tag) pairs, each measured against the decoder rather than
estimated.

Coverage is reported per pair, not per tag, because GEDCOM tag meaning depends
on where the tag appears. `+"`RELI`"+` under an individual and `+"`RELI`"+` under an event are
different structures, and this library may well support one and not the other. A
flat per-tag table would overstate support.

## Where the specification comes from

The inventory is the specification's own machine-readable structure list, not a
transcription: the `+"`extracted-files/`"+` directory of
[%s](%s), release %s, commit
[`+"`%s`"+`](%s/tree/%s/extracted-files),
vendored under `+"`testdata/spec/gedcom-7.0`"+`. It is %s-licensed; the required
`+"`NOTICE`"+` is vendored alongside it.

The files are test data. No library code reads them, and they add no runtime
dependency — this document is a report, not a parsing engine.

## How each status is derived

For every pair, `+"`decoder/spec7_coverage_test.go`"+` builds the smallest GEDCOM 7.0
document containing that structure in that context, and the same document with
that one line removed. It decodes both and reads three signals:

- **the typed model** — the header, schema, detected vendor, and each record's
  parsed entity. If it differs between the two documents, the structure has
  typed access. Every `+"`Tags`"+` field is excluded from the comparison: that is the
  raw half of [ADR 0003](../decisions/0003-lossless-dual-storage.md)'s dual
  storage and holds every line regardless of support, so counting it would
  report everything as supported. Line numbers are excluded for the same reason
  a control document is used at all — removing a line shifts the ones after it.
- **the diagnostics** — whether the decoder reported `+"`UNKNOWN_TAG`"+` for that line.
- **a sentinel tag** — `+"`ZZZZ`"+`, which no version of GEDCOM defines, placed in the
  same context. A decoder that reads a context must report the sentinel there.
  If it stays silent about the sentinel too, the context is not read at all, and
  silence about a standard tag says nothing. This is what separates
  `+"`raw (accepted)`"+` from `+"`raw (unwatched)`"+`, which are indistinguishable from the
  outside without it.

Two things worth stating plainly. A `+"`raw`"+` status never means data is lost:
[ADR 0003](../decisions/0003-lossless-dual-storage.md) keeps every line in
`+"`Record.Tags`"+`, and byte-for-byte round-tripping is a non-negotiable principle.
It means there is no typed field for it. And this measures the decoder only —
the encoder, validator and converter are not exercised here.

## What the numbers do not say

- **One context per structure, not every context.** A pair is measured at the
  shallowest place the specification allows it, so `+"`ADDR.CITY`"+` is measured under
  whichever record reaches `+"`ADDR`"+` first. If this library handled a structure
  under one record and not another, only the measured one is reported. The
  specification keys substructures the same way, so the inventory is no coarser
  than the standard it is derived from.
- **The level-0 column is the shallowest root, not the only one.** Many
  structures are reachable under several records; each is counted once, under
  the record its shortest path starts at.
- **`+"`typed`"+` is not a claim of completeness.** It means the structure changed the
  typed model, not that every part of its payload was interpreted.

## What is being done about the gaps

Everything below that is not `+"`typed`"+` was triaged when this report was first
published; the resulting issues are linked from
[issue #444](https://github.com/cacack/gedcom-go/issues/444). Read the table as
a statement of where the library is, not a backlog — the backlog lives in the
tracker.

## Regenerating

`+"```bash"+`
make spec-coverage
`+"```"+`

The document is checked in and compared on every test run, so a change in what
the decoder supports fails `+"`TestSpec7Coverage`"+` until it is regenerated.
`,
		len(entries),
		spec.source["repository"], spec.source["repository"], spec.source["release"],
		spec.source["commit"], spec.source["repository"], spec.source["commit"],
		spec.source["license"],
	)
}

// spec7Summary writes the overall counts and the per-record breakdown, which is
// what makes the document skimmable: it says where the gaps are concentrated
// before listing them.
func spec7Summary(entries []spec7Entry) string {
	var sb strings.Builder
	sb.WriteString("\n## Summary\n\n")

	overall := map[spec7Status]int{}
	for _, e := range entries {
		overall[e.status]++
	}

	sb.WriteString("| Status | Structures | Share | Meaning |\n")
	sb.WriteString("|--------|-----------:|------:|---------|\n")
	for _, status := range spec7StatusOrder {
		fmt.Fprintf(&sb, "| %s | %d | %s | %s |\n",
			status, overall[status], spec7Share(overall[status], len(entries)),
			spec7StatusMeaning[status])
	}

	sb.WriteString("\n### By top-level structure\n\n")
	sb.WriteString("The structure each pair is nested under at level 0.\n\n")

	byRoot := map[string]map[spec7Status]int{}
	totals := map[string]int{}
	for _, e := range entries {
		root := e.path[0].tag
		if byRoot[root] == nil {
			byRoot[root] = map[spec7Status]int{}
		}
		byRoot[root][e.status]++
		totals[root]++
	}

	roots := make([]string, 0, len(byRoot))
	for root := range byRoot {
		roots = append(roots, root)
	}
	sort.Slice(roots, func(i, j int) bool {
		if totals[roots[i]] != totals[roots[j]] {
			return totals[roots[i]] > totals[roots[j]]
		}
		return roots[i] < roots[j]
	})

	sb.WriteString("| Level 0 | Structures | Typed | Partial | Raw (accepted) | Raw (flagged) | Raw (unwatched) |\n")
	sb.WriteString("|---------|-----------:|------:|--------:|---------------:|--------------:|----------------:|\n")
	for _, root := range roots {
		counts := byRoot[root]
		fmt.Fprintf(&sb, "| `%s` | %d | %d | %d | %d | %d | %d |\n",
			root, totals[root], counts[spec7Typed], counts[spec7Partial],
			counts[spec7RawAccepted], counts[spec7RawFlagged], counts[spec7RawUnwatched])
	}

	return sb.String()
}

// spec7Share formats n out of total as a percentage.
func spec7Share(n, total int) string {
	if total == 0 {
		return "0.0%"
	}
	return fmt.Sprintf("%.1f%%", 100*float64(n)/float64(total))
}

// spec7Inventory writes the full table, one section per superstructure. Each
// section is headed by the nesting the entries were measured at, so a reader
// can reproduce any row by hand.
func spec7Inventory(entries []spec7Entry) string {
	groups := map[string]*spec7Group{}
	for _, e := range entries {
		context := e.context()
		if groups[context] == nil {
			groups[context] = &spec7Group{
				context: context,
				term:    spec7Term(e.pair.superstructure),
			}
		}
		groups[context].entries = append(groups[context].entries, e)
	}

	ordered := make([]*spec7Group, 0, len(groups))
	for _, g := range groups {
		ordered = append(ordered, g)
	}
	sort.Slice(ordered, func(i, j int) bool {
		// Top-level structures first; they are the entry point to everything
		// else, and their context is not a tag path.
		if (ordered[i].context == "(record)") != (ordered[j].context == "(record)") {
			return ordered[i].context == "(record)"
		}
		return ordered[i].context < ordered[j].context
	})

	var sb strings.Builder
	sb.WriteString("\n## Inventory\n\n")
	fmt.Fprintf(&sb, "%d superstructures, listed by the path a structure is reached at.\n",
		len(ordered))

	for _, g := range ordered {
		sort.Slice(g.entries, func(i, j int) bool {
			if g.entries[i].pair.tag != g.entries[j].pair.tag {
				return g.entries[i].pair.tag < g.entries[j].pair.tag
			}
			return g.entries[i].pair.structure < g.entries[j].pair.structure
		})

		if g.context == "(record)" {
			sb.WriteString("\n### Level 0\n\nStructures that appear at the top of a document.\n\n")
		} else {
			fmt.Fprintf(&sb, "\n### `%s`\n\nSubstructures of `%s`.\n\n", g.context, g.term)
		}

		sb.WriteString("| Tag | Structure | Status |\n")
		sb.WriteString("|-----|-----------|--------|\n")
		for _, e := range g.entries {
			fmt.Fprintf(&sb, "| `%s` | `%s` | %s |\n",
				e.pair.tag, spec7Term(e.pair.structure), e.status)
		}
	}

	return sb.String()
}
