package decoder

// spec55_report_test.go renders the derived GEDCOM 5.5 and 5.5.1 inventory as
// the published reference document. It makes no measurements of its own: every
// number below is counted from the rows spec55_coverage_test.go produced.

import (
	"fmt"
	"sort"
	"strings"
)

// joinTags renders a tag path the way the document writes it.
func joinTags(tags []string) string {
	return strings.Join(tags, ".")
}

// spec55Absent is what a version that does not define a structure shows.
const spec55Absent = "—"

// spec55Document renders the whole reference document.
func spec55Document(specs map[string]*spec55Spec, rows []*spec55Row) string {
	var sb strings.Builder

	sb.WriteString(spec55Preamble(specs, rows))
	sb.WriteString(spec55Summary(rows))
	sb.WriteString(spec55Defects(specs))
	sb.WriteString(spec55Inventory(rows))

	return sb.String()
}

// spec55Preamble writes the title, what the document is, and -- at more length
// than 7.0's needs -- where its inventory came from, since unlike 7.0 there was
// no machine-readable inventory to start from.
func spec55Preamble(specs map[string]*spec55Spec, rows []*spec55Row) string {
	var provenance strings.Builder
	for _, edition := range spec55Editions {
		s := specs[edition.version]
		fmt.Fprintf(&provenance,
			"| %s | [`%s`](%s) | `%s` | %s |\n",
			edition.version, spec55File(s.source["url"]), s.source["url"],
			spec55ShortHash(s.source["sha256"]), s.source["retrieved"])
	}

	var notices strings.Builder
	for _, edition := range spec55Editions {
		fmt.Fprintf(&notices, "> **%s** — %s\n>\n", edition.version,
			specs[edition.version].source["copyright"])
	}

	perVersion := make([]string, 0, len(spec55Editions))
	distinct := map[[2]string]bool{}
	for _, edition := range spec55Editions {
		n := 0
		for _, row := range rows {
			if _, ok := row.measured[edition.version]; ok {
				n++
				distinct[[2]string{row.superstructure, row.tag}] = true
			}
		}
		perVersion = append(perVersion, fmt.Sprintf("%d in %s", n, edition.version))
	}

	return fmt.Sprintf(`<!-- Generated by decoder/spec55_coverage_test.go. Do not edit by hand. -->

# GEDCOM 5.5 and 5.5.1 coverage

What this library does with every structure GEDCOM 5.5 and 5.5.1 define, in
every context they define it: %d rows across the two versions — %s —
each measured against the decoder rather than estimated. The GEDCOM 7.0 half
is [a separate document](gedcom-7-coverage.md), derived the same way.

Coverage is reported per context, not per tag, because GEDCOM tag meaning
depends on where the tag appears. `+"`RELI`"+` under an individual and `+"`RELI`"+` under an
event are different structures, and this library may well support one and not
the other. A flat per-tag table would overstate support.

A row is a (superstructure, tag, structure) triple rather than a
(superstructure, tag) pair, and the two are not the same count here: these
grammars alternate, so one tag can name two different structures under one
parent — `+"`NOTE`"+` under an event is either a pointer to a note record or inline
text — and each is measured separately because this library may support one and
not the other. The %d rows are %d distinct (superstructure, tag) pairs.

The two versions are reported together because they share most of a grammar.
Where they agree, one row says so; where they differ, the row shows it.

## Where the specification comes from

7.0 is published with machine-readable extracted files. 5.5 and 5.5.1 are not:
their structure set exists only as the semi-formal Lineage-Linked Grammar
printed in Chapter 2 of each specification, which states tag, nesting,
cardinality, value type and cross-reference target — everything an inventory
needs — as typeset text.

`+"`scripts/spec55/transcribe.py`"+` reads those chapters and writes the files 7.0
ships, under `+"`testdata/spec/gedcom-5.5`"+` and `+"`testdata/spec/gedcom-5.5.1`"+`.

Neither PDF is vendored, and neither is its prose. What is checked in is the
*facts* read out of them — tag, superstructure, cardinality, value type — plus
the individual grammar lines the defect table below has to quote to say what is
wrong with them. Each document states its own terms, and `+"`SOURCE`"+` records those
verbatim rather than paraphrasing:

| Version | Document | SHA-256 | Retrieved |
|---------|----------|---------|-----------|
%s
%s
A transcription is only as good as its proofreading, so
`+"`scripts/spec55/crosscheck.py`"+` checks it against two sources made without
reference to it: the 5.5 specification's own Appendix B, which lists every place
each substructure is spliced, and
[pjcj/Gedcom.pm](https://github.com/pjcj/Gedcom.pm)'s `+"`.grammar`"+` files, which are
someone else's transcription of the same chapters. Gedcom.pm is Perl-licensed
and nothing is copied from it; it is read and compared. The differences that
remain are listed in
[`+"`testdata/spec/README.md`"+`](../../testdata/spec/README.md), and each is a place
Gedcom.pm departs from the printed grammar where this follows it: mostly
structures it adds, two where it harmonizes an inconsistency 5.5.1 has with
itself, and one that is a difference in naming rather than in what the grammar
allows.

The files are test data. No library code reads them, and they add no runtime
dependency — this document is a report, not a parsing engine.

## How each status is derived

Identically to the 7.0 report, by `+"`decoder/spec_common_test.go`"+`, which both
harnesses share. For every pair it builds the smallest document of that version
containing the structure in that context, and the same document with that one
line removed. It decodes both and reads three signals:

- **the typed model** — the header, schema, detected vendor, and each record's
  parsed entity. If it differs between the two documents, the structure has
  typed access. Every `+"`Tags`"+` field is excluded from the comparison: that is the
  raw half of [ADR 0003](../decisions/0003-lossless-dual-storage.md)'s dual
  storage and holds every line regardless of support, so counting it would
  report everything as supported.
- **the diagnostics** — whether the decoder reported `+"`UNKNOWN_TAG`"+` for that line.
- **a sentinel tag** — `+"`ZZZZ`"+`, which no version of GEDCOM defines, placed in the
  same context. A context that reports the sentinel reports unknown tags at all;
  one that stays silent about the sentinel is silent about everything, so silence
  about a standard tag there says nothing. This separates `+"`raw (accepted)`"+` from
  `+"`raw (undiagnosed)`"+`, which are indistinguishable from the outside without it.

A `+"`raw`"+` status means there is no typed field for the structure, not that the
structure is dropped: every line is kept in `+"`Record.Tags`"+` under
[ADR 0003](../decisions/0003-lossless-dual-storage.md), whether the decoder
understands it or not. This report measures the decoder alone; the encoder,
validator and converter are not exercised here.

## Structure names

A 5.5.x structure is named for the grammar production that defines it and the
path of tags to it inside that production — `+"`EVENT_DETAIL.DATE`"+` is the `+"`DATE`"+`
line of `+"`EVENT_DETAIL`"+`. That is the same identity 7.0's URIs carry, spelled the
way these specifications name things: one structure stays one structure however
many places splice it in.

Two suffixes appear. A `+"`#2`"+` marks the second branch of an alternation that
reuses a tag — both specifications define `+"`NOTE`"+` twice in `+"`NOTE_STRUCTURE`"+`, once
as a pointer to a note record and once as inline text — and the two are
genuinely different structures that this library may support separately. A
production name inside the path, as in
`+"`FAM_RECORD.FAM.FAMILY_EVENT_STRUCTURE.HUSB`"+`, marks a line 5.5 writes beneath a
splice: `+"`HUSB`"+` there is a substructure of every family event tag, which is
exactly what 5.5.1 later named `+"`FAMILY_EVENT_DETAIL`"+`.

## What the numbers do not say

- **One context per structure, not every context.** A pair is measured at the
  shallowest place the grammar allows it. If this library handled a structure
  under one record and not another, only the measured one is reported.
- **The cardinality column is the grammar's, not a rule this library enforces.**
  It is recorded because the grammar states it. Nothing here validates against
  it; that is [ADR 0008](../decisions/0008-validator-architecture.md)'s territory
  and separate work.
- **A value the decoder would have chosen anyway is invisible.** The measurement
  is a difference between two decoded documents, so a line whose only typed
  effect is a value the model already holds cannot be seen. 5.5 is where this
  bites: the decoder falls back to 5.5 when a document states no version, so
  removing the version statement from a 5.5 document changes nothing, and
  `+"`HEAD`"+`, `+"`HEAD.GEDC`"+` and `+"`HEAD.GEDC.VERS`"+` read `+"`raw (undiagnosed)`"+` in 5.5 and
  `+"`typed`"+` in 5.5.1. The difference between those two columns is the fallback,
  not the decoder. `+"`TestSpec55VersionFallbackIsInvisible`"+` pins it so this note
  cannot quietly stop being true.
- **`+"`typed`"+` is not a claim of completeness.** It means the structure changed the
  typed model, not that every part of its payload was interpreted.
- **Every payload is invented.** The grammar names a value type; it does not
  supply an example. The harness synthesizes one. A decoder that accepted one
  plausible value and rejected another would be measured on the value it was
  given.
- **The drift test proves the report matches the decoder, not that the decoder is
  right.** A behaviour change fails it; a behaviour that was always wrong does
  not.

## What is being done about the gaps

Everything below that is not `+"`typed`"+` was triaged when this report was first
published, against the issues the 7.0 report had already raised. Most of it was
already tracked: attribute substructures reported as unknown ([#402]), event
detail dropping `+"`RELI`"+` ([#447]), family `+"`CENS`"+` and `+"`RESI`"+` never decoded
([#448]), and the header emitting no diagnostics at all ([#449]) between them
account for the bulk of the non-typed rows.

Two gaps were new, and neither could have come from the 7.0 half:

- **[#452]** — submission records reach no typed field at all. 7.0 removed
  `+"`SUBN`"+`, so only a 5.5.x inventory can show it.
- **[#453]** — 5.5.1's `+"`FONE`"+` and `+"`ROMN`"+` name variations are recognized and
  then dropped, where 7.0's equivalent `+"`TRAN`"+` is parsed into the typed model.

Read the table as a statement of where the library is, not as a backlog — the
backlog lives in the tracker.

[#402]: https://github.com/cacack/gedcom-go/issues/402
[#447]: https://github.com/cacack/gedcom-go/issues/447
[#448]: https://github.com/cacack/gedcom-go/issues/448
[#449]: https://github.com/cacack/gedcom-go/issues/449
[#452]: https://github.com/cacack/gedcom-go/issues/452
[#453]: https://github.com/cacack/gedcom-go/issues/453

## Regenerating

`+"```bash"+`
make spec-coverage
`+"```"+`

The document is checked in and compared on every test run, so a change in what
the decoder supports fails `+"`TestSpec55Coverage`"+` until it is regenerated. The
inventory itself is regenerated only by re-running the transcription against the
specification PDFs, which is described in
[`+"`scripts/spec55/README.md`"+`](../../scripts/spec55/README.md).
`,
		len(rows), strings.Join(perVersion, " and "), len(rows), len(distinct),
		provenance.String(), notices.String(),
	)
}

// spec55File reduces a URL to the file name a reader recognizes.
func spec55File(url string) string {
	if i := strings.LastIndex(url, "/"); i >= 0 {
		return url[i+1:]
	}
	return url
}

// spec55ShortHash abbreviates a digest to something a reader can compare at a
// glance; the full value is in the SOURCE file.
func spec55ShortHash(hash string) string {
	if len(hash) > 16 {
		return hash[:16] + "…"
	}
	return hash
}

// spec55Summary writes the overall counts per version, and the per-record
// breakdown, which is what makes the document skimmable: it says where the gaps
// are concentrated before listing them.
func spec55Summary(rows []*spec55Row) string {
	var sb strings.Builder
	sb.WriteString("\n## Summary\n\n")

	counts := map[string]map[specStatus]int{}
	totals := map[string]int{}
	for _, edition := range spec55Editions {
		counts[edition.version] = map[specStatus]int{}
	}
	for _, row := range rows {
		for version, m := range row.measured {
			counts[version][m.status]++
			totals[version]++
		}
	}

	sb.WriteString("| Status |")
	for _, edition := range spec55Editions {
		fmt.Fprintf(&sb, " %s | Share |", edition.version)
	}
	sb.WriteString(" Meaning |\n|--------|")
	for range spec55Editions {
		sb.WriteString("------:|------:|")
	}
	sb.WriteString("---------|\n")
	for _, status := range specStatusOrder {
		fmt.Fprintf(&sb, "| %s |", status)
		for _, edition := range spec55Editions {
			n := counts[edition.version][status]
			fmt.Fprintf(&sb, " %d | %s |", n, specShare(n, totals[edition.version]))
		}
		fmt.Fprintf(&sb, " %s |\n", specStatusMeaning[status])
	}
	sb.WriteString("| **total** |")
	for _, edition := range spec55Editions {
		fmt.Fprintf(&sb, " **%d** | 100.0%% |", totals[edition.version])
	}
	sb.WriteString(" |\n")

	sb.WriteString("\n### By top-level structure\n\n")
	sb.WriteString("The structure each pair is nested under at level 0, and how many\n" +
		"pairs under it reach the typed model.\n\n")

	byRoot := map[string]map[string][2]int{} // root -> version -> {typed, total}
	for _, row := range rows {
		for _, edition := range spec55Editions {
			root := row.root(edition.version)
			if root == "" {
				continue
			}
			if byRoot[root] == nil {
				byRoot[root] = map[string][2]int{}
			}
			counts := byRoot[root][edition.version]
			counts[1]++
			if row.measured[edition.version].status == specTyped {
				counts[0]++
			}
			byRoot[root][edition.version] = counts
		}
	}

	roots := make([]string, 0, len(byRoot))
	for root := range byRoot {
		roots = append(roots, root)
	}
	sort.Strings(roots)

	sb.WriteString("| Level 0 |")
	for _, edition := range spec55Editions {
		fmt.Fprintf(&sb, " %s typed / total |", edition.version)
	}
	sb.WriteString("\n|---------|")
	for range spec55Editions {
		sb.WriteString("----------------:|")
	}
	sb.WriteString("\n")
	for _, root := range roots {
		fmt.Fprintf(&sb, "| `%s` |", root)
		for _, edition := range spec55Editions {
			counts, ok := byRoot[root][edition.version]
			if !ok {
				fmt.Fprintf(&sb, " %s |", spec55Absent)
				continue
			}
			fmt.Fprintf(&sb, " %d / %d |", counts[0], counts[1])
		}
		sb.WriteString("\n")
	}

	return sb.String()
}

// spec55Defects writes what the transcription found wrong with the
// specification text. Publishing it is the point: a reader comparing this
// inventory against their own copy of the PDF needs to know where the printed
// grammar does not say what it means, and what was read instead.
func spec55Defects(specs map[string]*spec55Spec) string {
	var sb strings.Builder
	sb.WriteString("\n## Defects in the specification text\n\n")
	sb.WriteString("Places the printed grammar does not say what it means, and the reading\n" +
		"taken. Nothing here is corrected in the inventory — a transcription that\n" +
		"quietly repaired its source would be a different document than the one it\n" +
		"claims to describe.\n\n")

	type defect struct {
		spec55Defect
		versions []string
	}
	seen := map[[4]string]*defect{}
	var order [][4]string
	for _, edition := range spec55Editions {
		for _, d := range specs[edition.version].defects {
			key := [4]string{d.block, d.line, d.problem, d.reading}
			if _, ok := seen[key]; !ok {
				seen[key] = &defect{spec55Defect: d}
				order = append(order, key)
			}
			seen[key].versions = append(seen[key].versions, edition.version)
		}
	}
	sort.Slice(order, func(i, j int) bool {
		for k := range order[i] {
			if order[i][k] != order[j][k] {
				return order[i][k] < order[j][k]
			}
		}
		return false
	})

	sb.WriteString("| Versions | Production | As printed | Problem | Read as |\n")
	sb.WriteString("|----------|------------|------------|---------|---------|\n")
	for _, key := range order {
		d := seen[key]
		fmt.Fprintf(&sb, "| %s | `%s` | `%s` | %s | %s |\n",
			strings.Join(d.versions, ", "), d.block, d.line, d.problem, d.reading)
	}

	return sb.String()
}

// spec55Inventory writes the full table, one section per superstructure. Each
// section is headed by the nesting the entries were measured at, so a reader
// can reproduce any row by hand.
func spec55Inventory(rows []*spec55Row) string {
	type group struct {
		superstructure string
		rows           []*spec55Row
	}

	groups := map[string]*group{}
	var order []string
	for _, row := range rows {
		g, ok := groups[row.superstructure]
		if !ok {
			g = &group{superstructure: row.superstructure}
			groups[row.superstructure] = g
			order = append(order, row.superstructure)
		}
		g.rows = append(g.rows, row)
	}

	var sb strings.Builder
	sb.WriteString("\n## Inventory\n\n")
	fmt.Fprintf(&sb, "%d superstructures, listed by the production that defines each.\n",
		len(order))

	for _, key := range order {
		g := groups[key]
		if g.superstructure == "" {
			sb.WriteString("\n### Level 0\n\nStructures that appear at the top of a document.\n\n")
		} else {
			fmt.Fprintf(&sb, "\n### `%s`\n\n%s\n\n",
				g.superstructure, spec55Nesting(g.rows))
		}

		sb.WriteString("| Tag | Structure |")
		for _, edition := range spec55Editions {
			fmt.Fprintf(&sb, " %s |", edition.version)
		}
		sb.WriteString(" Cardinality |\n|-----|-----------|")
		for range spec55Editions {
			sb.WriteString("--------|")
		}
		sb.WriteString("-------------|\n")

		for _, row := range g.rows {
			fmt.Fprintf(&sb, "| `%s` | `%s` |", row.tag, row.structure)
			for _, edition := range spec55Editions {
				m, ok := row.measured[edition.version]
				if !ok {
					fmt.Fprintf(&sb, " %s |", spec55Absent)
					continue
				}
				fmt.Fprintf(&sb, " %s |", m.status)
			}
			fmt.Fprintf(&sb, " %s |\n", spec55Cardinality(row))
		}
	}

	return sb.String()
}

// spec55Nesting describes where a group's structures were measured, naming each
// version separately when the two reach the superstructure by different paths.
//
// Every row is consulted, not just the first. A group's first row can be one a
// single version defines -- MULTIMEDIA_RECORD's is BLOB, which 5.5.1 dropped --
// and reading the nesting off that row would attribute the whole section to the
// one version that happens to define its first tag.
func spec55Nesting(rows []*spec55Row) string {
	byContext := map[string][]string{}
	var order []string
	for _, edition := range spec55Editions {
		context := ""
		for _, row := range rows {
			if c := row.context(edition.version); c != "" {
				context = c
				break
			}
		}
		if context == "" {
			continue
		}
		if _, ok := byContext[context]; !ok {
			order = append(order, context)
		}
		byContext[context] = append(byContext[context], edition.version)
	}

	parts := make([]string, 0, len(order))
	for _, context := range order {
		parts = append(parts, fmt.Sprintf("`%s` in %s",
			context, strings.Join(byContext[context], ", ")))
	}
	return "Measured at " + strings.Join(parts, "; ") + "."
}

// spec55Cardinality renders what the grammar allows, naming the versions
// separately when they differ.
func spec55Cardinality(row *spec55Row) string {
	byValue := map[string][]string{}
	var order []string
	for _, edition := range spec55Editions {
		m, ok := row.measured[edition.version]
		if !ok {
			continue
		}
		value := m.cardinality
		if value == "" {
			// A line stating no cardinality that no splice reaches either.
			// Neither document has one today: the two lines that state none are
			// both reached through a splice, so they inherit its bound, which
			// is what the defect table above records.
			value = "not stated"
		}
		if _, seen := byValue[value]; !seen {
			order = append(order, value)
		}
		byValue[value] = append(byValue[value], edition.version)
	}

	if len(order) == 1 {
		return spec55Range(order[0])
	}
	parts := make([]string, 0, len(order))
	for _, value := range order {
		parts = append(parts, fmt.Sprintf("%s in %s",
			spec55Range(value), strings.Join(byValue[value], ", ")))
	}
	return strings.Join(parts, "; ")
}

// spec55Range renders a cardinality the way the grammar writes it.
func spec55Range(value string) string {
	if value == "not stated" {
		return value
	}
	return "`{" + value + "}`"
}
